name: signature_example
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # display signature
  signature: ^5.0.0
  path_provider: ^2.0.8
  googleapis_auth: ^1.3.0
  url_launcher: ^6.0.18
  googleapis: ^7.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true